global_frame: odom
rolling_window: true
track_unknown_space: false

plugins:
  - {name: no_go_zones,               type: "costmap_2d::StaticLayer"}
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
